---
# yamllint disable rule:line-length
###############################################################################
# Atomically write INI files.
###############################################################################
# Writes a given INI file containing duplicate keys atomically.
#
# This is used in the case of INI files which contain duplicate keys (e.g. UE4
# games). INI files that contain duplicate keys violate the INI standard. Files
# are written to temp file with exclusive disabled, then moved into place,
# preventing infinite duplicate key growth in configs.
#
# This should only be used for INI files meeting this specific case; standard
# cases should ALWAYS use community.general.ini_file directly in configuration
# tasks.
#
# Args:
#   ini: list of dict - INI configuration.
#     - section: str - INI section heading to use.
#       option: str - INI section option.
#       value: any - INI section value (cast to string).
#       state: str - Add or remove specified key.
#           Values:
#             present: specified option=values lines are added, but other
#                      options with the same name are not touched.
#              absent: specified option=value lines are removed, but other
#                      options with the same name are not touched.
#       comment: str - Setting comment. Optional.
#
# Additional supported arguments mirror community.general.ini_file:
#   allow_no_value: bool - Allow option without value and without =.
#       Default: False.
#   attributes: str - Attributes resulting filesystem object should have in the
#         same order as the one displayed by lsattr. The = operator is assumed
#         as default, otherwise + or - operators need to be included in string.
#       Default: omit.
#   backup: bool - Create backup file with timestamp on change?
#       Default: False.
#   create: bool - Fail if file does not already exist.
#       Default: True.
#   follow: bool - Follow symlinks if they exist.
#       Default: False.
#   group: str - Group that owns filesystem object, per chown. Current group of
#         current user is used when unspecified, unless root in which case it
#         can preserve previous ownership.
#       Default: omit.
#   ignore_spaces: bool - Do not change line if doing so would only add or
#         remove spaces before or after =.
#       Default: False.
#   mode: str - Octal file permissions. Umask used if file created and mode not
#         specified, otherwise permissions are kept.
#       Default: omit.
#   modify_inactive_option: bool - Replace commented line that matches given
#         option.
#       Default: True.
#   no_extra_spaces: bool - Do not insert spaces before and after =.
#       Default: False.
#   owner: str - User name owning filesystem object, per chown. Current name of
#         current user is used when unspecified, unless root in which case it
#         can preserve previous ownership.
#       Default: omit.
#   path: str - Path to INI-style file; this file is created if required.
#   section_has_values: list of dict - With state=present, if a suitable
#         section is not found, a new section is added, including required
#         options. With state=absent, at most one section is removed if it
#         contains the values.
#       Default: 'present'.
#   selevel: str - SELinux filesystem object context level.
#       Default: omit.
#   serole: str - SELinux filesystem object context role.
#       Default: omit.
#   setype: str - SELinux filesystem object context type.
#       Default: omit.
#   seuser: str - SELinux filesystem object context user.
#       Default: omit.
#   unsafe_writes: bool - Use atomic operation to prevent data corruption or
#         inconsistent reads from the target filesystem object. This atomic
#         operation is different from atomic_ini (per write vs. per file).
#       Default: False.
#   check_mode: bool - Return status prediction without modifying target.
#       Default: False.
#   diff: bool - Return details on change.
#       Default: False.
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html
# yamllint enable rule:line-length

- name: 'Atomic INI | stage'
  when: ini | length > 0
  community.general.ini_file:  # noqa name[template] filename
    allow_no_value: '{{ allow_no_value | default(false) }}'
    attributes: '{{ attributes | default(omit) }}'
    backup: '{{ backup | default(false) }}'
    create: '{{ create | default(true) }}'
    exclusive: false
    follow: '{{ follow | default(false) }}'
    group: '{{ group | default(omit) }}'
    ignore_spaces: '{{ ignore_spaces | default(false) }}'
    mode: '{{ mode | default(omit) }}'
    modify_inactive_option: '{{ modify_inactive_option | default(true) }}'
    no_extra_spaces: '{{ no_extra_spaces | default(false) }}'
    option: '{{ item.option }}'
    owner: '{{ owner | default(omit) }}'
    path: '{{ "/tmp/" ~ inventory_hostname ~ ".atomic_ini" }}'
    section: '{{ item.section }}'
    section_has_values: '{{ section_has_values | default(omit) }}'
    selevel: '{{ selevel | default(omit) }}'
    serole: '{{ serole | default(omit) }}'
    setype: '{{ setype | default(omit) }}'
    seuser: '{{ seuser | default(omit) }}'
    state: '{{ item.state | default("present") }}'
    unsafe_writes: '{{ unsafe_writes | default(false) }}'
    value: '{{ item.value | string }}'
  check_mode: '{{ check_mode | default(false) }}'
  diff: '{{ diff | default(false) }}'
  loop: '{{ ini }}'

- name: 'Atomic INI | set {{ path }}'
  when: ini | length > 0
  ansible.builtin.copy:
    src: '{{ "/tmp/" ~ inventory_hostname ~ ".atomic_ini" }}'
    remote_src: true
    dest: '{{ path }}'
    owner: '{{ owner | default(omit) }}'
    group: '{{ group | default(omit) }}'
    mode: '{{ mode | default(omit) }}'
    force: true
  check_mode: '{{ check_mode | default(false) }}'
  diff: '{{ diff | default(false) }}'

- name: 'Atomic INI | unstage'
  ansible.builtin.file:
    path: '{{ "/tmp/" ~ inventory_hostname ~ ".atomic_ini" }}'
    state: 'absent'
  check_mode: '{{ check_mode | default(false) }}'
  diff: '{{ diff | default(false) }}'
